resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/redhat-appstudio/release-service/config/default?ref=4f70c35199e4b0eabfad87ecd258d5db0a86b26f
  - .tekton/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/release-service
    newName: quay.io/redhat-appstudio/release-service
    newTag: 4f70c35199e4b0eabfad87ecd258d5db0a86b26f
namespace: release-service
patches:
  - ./manager_resources_patch.yaml
