resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/redhat-appstudio/integration-service/config/default?ref=d98f87bb2631bf5909d1152a27599cedd436cf19
  - .tekton/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/redhat-appstudio/integration-service
    newTag: d98f87bb2631bf5909d1152a27599cedd436cf19
namespace: integration-service
patches:
  - ./manager_resources_patch.yaml
